version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ranter
    volumes:
      - db_data:/var/lib/postgresql/data
  prisma:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5555:5555'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npx prisma studio
    links:
      - db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: >
      sh -c "npx prisma migrate dev --name init && yarn start"
volumes:
  db_data:
